import type { Product } from "./types";

export type { Product };

function p(
  brand: string,
  series: string | null,
  name: string,
  nicotine: number,
  price: number,
  folder: string,
  file: string,
): Product {
  return { id: `${folder}/${file}`, brand, series, name, nicotine, price, folder, file };
}

export const BRANDS = [
  "Blue Magic",
  "Corvus",
  "FEDRS",
  "KASTA",
  "KASTA ANIME",
  "KASTA COVID",
  "KASTA DOTA",
  "KASTA FOBIA",
  "KASTA LE",
  "LastOfUs",
  "LYFT",
  "RED",
  "SIBERIA",
  "ST",
  "ST вата",
  "VELO",
  "VOLKI",
  "Стиль",
] as const;

export type BrandName = (typeof BRANDS)[number];

export const products: Product[] = [
  p("Blue Magic", null, "Blue Raspberry Jam", 12, 510, "Blue Magic", "Blue Raspberry Jam"),
  p("Blue Magic", null, "Cherry Juice", 12, 550, "Blue Magic", "Cherry Juice"),
  p("Blue Magic", null, "Crazy Mint", 12, 550, "Blue Magic", "Crazy Mint"),
  p("Blue Magic", null, "Lime Watermelon", 12, 550, "Blue Magic", "Lime Watermelon"),
  p("Blue Magic", null, "Mango Shake", 12, 540, "Blue Magic", "Mango Shake"),

  p("Corvus", null, "Brutal Menthol", 14, 530, "Corvus", "BRUTAL MENTHOL"),
  p("Corvus", null, "CHN", 14, 510, "Corvus", "CHN"),
  p("Corvus", null, "Extreme Menthol", 14, 530, "Corvus", "EXTREME MENTHOL"),
  p("Corvus", null, "Fenix Barberry", 14, 540, "Corvus", "FENIX BARBERRY"),
  p("Corvus", null, "Flash Orange", 14, 520, "Corvus", "FLASH ORANGE"),
  p("Corvus", null, "Hulk Fejoa", 14, 500, "Corvus", "HULK FEJOA"),
  p("Corvus", null, "Joker Wild Berries", 14, 510, "Corvus", "JOKER WILD BERRIES"),
  p("Corvus", null, "Logan Melon", 14, 550, "Corvus", "LOGAN MELON"),

  p("FEDRS", null, "Doble Mint Hard 9", 50, 530, "FEDRS", "Doble Mint Hard 9"),
  p("FEDRS", null, "Freeze Mint Hard 9", 50, 520, "FEDRS", "Freeze Mint Hard 9"),
  p("FEDRS", null, "ICE COOL Banana Hard", 50, 520, "FEDRS", "ICE COOL Banana Hard"),
  p("FEDRS", null, "ICE COOL Mint Extra Strong 8", 40, 510, "FEDRS", "ICE COOL Mint Extra Strong 8"),
  p("FEDRS", null, "ICE COOL Mint Hard", 50, 510, "FEDRS", "ICE COOL Mint Hard"),
  p("FEDRS", null, "ICE COOL Mint Strong 5", 20, 520, "FEDRS", "ICE COOL Mint Strong 5"),
  p("FEDRS", null, "Mint Hard 10", 60, 500, "FEDRS", "Mint Hard 10"),
  p("FEDRS", null, "Mint Hard 9", 50, 500, "FEDRS", "Mint Hard 9"),
  p("FEDRS", null, "Strawberry Bubble Hard 8", 40, 530, "FEDRS", "Strawberrt Bubble Hard 8"),
  p("FEDRS", null, "Ultra Mint Hard 9", 50, 500, "FEDRS", "Ultra Mint Hard 9"),
  p("FEDRS", null, "Watermelon Bubble Hard 8", 40, 520, "FEDRS", "Watermelon Bubble Hard 8"),

  p("KASTA", null, "Абрикос", 13, 520, "KASTA", "Абрикос"),
  p("KASTA", null, "Ананас", 13, 540, "KASTA", "Ананас"),
  p("KASTA", null, "Арбуз", 13, 520, "KASTA", "Арбуз"),
  p("KASTA", null, "Банан", 13, 500, "KASTA", "Банан"),
  p("KASTA", null, "Bubble Gum", 13, 510, "KASTA", "Bubble Gum"),
  p("KASTA", null, "Вишня", 13, 550, "KASTA", "Вишня"),
  p("KASTA", null, "Гранат", 13, 530, "KASTA", "Гранат"),
  p("KASTA", null, "Груша", 13, 540, "KASTA", "Груша"),
  p("KASTA", null, "Гуава", 13, 500, "KASTA", "Гуава"),
  p("KASTA", null, "Дыня", 13, 530, "KASTA", "Дыня"),
  p("KASTA", null, "Ежевика", 13, 500, "KASTA", "Ежевика"),
  p("KASTA", null, "Зефир", 13, 540, "KASTA", "Зефир"),
  p("KASTA", null, "Киви", 13, 520, "KASTA", "Киви"),
  p("KASTA", null, "Клубника", 13, 550, "KASTA", "Клубника"),
  p("KASTA", null, "Мята", 13, 540, "KASTA", "Мята"),
  p("KASTA", null, "Персик с мёдом", 13, 520, "KASTA", "Персик с медом"),
  p("KASTA", null, "Слива", 13, 540, "KASTA", "Слива"),
  p("KASTA", null, "Сливочный пломбир", 13, 510, "KASTA", "Сливочный пломбир"),
  p("KASTA", null, "Тропик микс", 13, 550, "KASTA", "Тропик микс"),
  p("KASTA", null, "Чёрная смородина", 13, 500, "KASTA", "Черная смородина"),
  p("KASTA", null, "Черничный пирог", 13, 500, "KASTA", "Черничный пирог"),
  p("KASTA", null, "Энерджи", 13, 550, "KASTA", "Энерджи"),

  p("KASTA ANIME", null, "Guy", 13, 520, "KASTA ANIME", "Guy"),
  p("KASTA ANIME", null, "Hashirama", 13, 500, "KASTA ANIME", "Hashirama"),
  p("KASTA ANIME", null, "Itachi", 13, 510, "KASTA ANIME", "Itachi"),
  p("KASTA ANIME", null, "Jiraya", 13, 500, "KASTA ANIME", "Jiraya"),
  p("KASTA ANIME", null, "Kakashi", 13, 530, "KASTA ANIME", "Kakashi"),
  p("KASTA ANIME", null, "Madara", 13, 520, "KASTA ANIME", "Madara"),
  p("KASTA ANIME", null, "Minato", 13, 530, "KASTA ANIME", "Minato"),
  p("KASTA ANIME", null, "Naruto", 13, 550, "KASTA ANIME", "Naruto"),
  p("KASTA ANIME", null, "Obito", 13, 520, "KASTA ANIME", "Obito"),
  p("KASTA ANIME", null, "Pain", 13, 510, "KASTA ANIME", "Pain"),
  p("KASTA ANIME", null, "Sasuke", 13, 520, "KASTA ANIME", "Sasuke"),
  p("KASTA ANIME", null, "Templar Assassin", 13, 520, "KASTA ANIME", "Templar Assassin"),
  p("KASTA ANIME", null, "Tobirama", 13, 510, "KASTA ANIME", "Tobirama"),

  p("KASTA COVID", null, "Ванильный диагноз с колой", 13, 550, "KASTA COVID", "Ванильный диагноз с колой"),
  p("KASTA COVID", null, "Вирус мохито", 13, 520, "KASTA COVID", "Вирус мохито"),
  p("KASTA COVID", null, "Грейпфрутовая вакцинация", 13, 550, "KASTA COVID", "Грейпфрутовая вакцинация"),
  p("KASTA COVID", null, "Имбирная лихорадка", 13, 550, "KASTA COVID", "Имбирная лихорадка"),
  p("KASTA COVID", null, "Локдаун манго личи", 13, 550, "KASTA COVID", "Локдаун манго личи"),
  p("KASTA COVID", null, "Малиновая самоизоляция", 13, 500, "KASTA COVID", "Малиновая самоизоляция"),
  p("KASTA COVID", null, "Нектариновый омикрон", 13, 540, "KASTA COVID", "Нектариновый омикрон"),
  p("KASTA COVID", null, "Озноб — виноградный лимонад", 13, 550, "KASTA COVID", "Озноб - виноградный лимонад"),
  p("KASTA COVID", null, "Пиф с малиновым пончиком", 13, 510, "KASTA COVID", "Пиф с малиновым пончиком"),
  p("KASTA COVID", null, "Психоз из абсента", 13, 540, "KASTA COVID", "Психоз из абсента"),
  p("KASTA COVID", null, "Сливочно-клубничный вирус", 13, 550, "KASTA COVID", "Сливочно-клубничный вирус"),
  p("KASTA COVID", null, "Фисташковый спутник", 13, 510, "KASTA COVID", "Фисташковый спутник"),
  p("KASTA COVID", null, "Хворь из лесных ягод", 13, 510, "KASTA COVID", "Хворь из лесных ягод"),
  p("KASTA COVID", null, "Штамм баблгамма и манго", 13, 530, "KASTA COVID", "Штамм баблгамма и манго"),
  p("KASTA COVID", null, "Яблочный сок", 13, 530, "KASTA COVID", "Яблочный сок"),

  p("KASTA DOTA", null, "Bloodseeker", 13, 520, "KASTA DOTA", "BLOODSEEKER"),
  p("KASTA DOTA", null, "Dazzle", 13, 550, "KASTA DOTA", "DAZZLE"),
  p("KASTA DOTA", null, "Drow Ranger", 13, 550, "KASTA DOTA", "DROW RANGER"),
  p("KASTA DOTA", null, "Invoker", 13, 540, "KASTA DOTA", "INVOKER"),
  p("KASTA DOTA", null, "Monkey King", 13, 510, "KASTA DOTA", "MONKEY KING"),
  p("KASTA DOTA", null, "Puck", 13, 550, "KASTA DOTA", "PUCK"),
  p("KASTA DOTA", null, "Pudge", 13, 520, "KASTA DOTA", "PUDGE"),
  p("KASTA DOTA", null, "Shadow Fiend", 13, 500, "KASTA DOTA", "SHADOW FIEND"),
  p("KASTA DOTA", null, "Wraith King", 13, 510, "KASTA DOTA", "WRAITH KING"),

  p("KASTA FOBIA", null, "Cherry Limonade", 20, 530, "KASTA FOBIA", "Cherry Limonade"),
  p("KASTA FOBIA", null, "Citron Ice", 20, 520, "KASTA FOBIA", "Citron Ice"),
  p("KASTA FOBIA", null, "Orange Candy", 20, 500, "KASTA FOBIA", "Orange Candy"),
  p("KASTA FOBIA", null, "Tropic Bubble Gum", 20, 510, "KASTA FOBIA", "Tropic Bubble Gum"),
  p("KASTA FOBIA", null, "Лимон", 20, 500, "KASTA FOBIA", "Лимон"),
  p("KASTA FOBIA", null, "Яблоко", 20, 520, "KASTA FOBIA", "Яблоко"),

  p("KASTA LE", null, "Банан-Шоколад", 13, 540, "KASTA LE", "Банан-Шоколад"),
  p("KASTA LE", null, "Глинтвейн", 13, 550, "KASTA LE", "Глинтвейн"),
  p("KASTA LE", null, "Мандарин", 13, 520, "KASTA LE", "Мандарин"),
  p("KASTA LE", null, "Спрайт", 13, 510, "KASTA LE", "Спрайт"),

  p("LastOfUs", null, "Frosty Mint", 16, 510, "LastOfUs", "Frosty Mint"),
  p("LastOfUs", null, "Pepper Mint", 16, 550, "LastOfUs", "Pepper Mint"),

  p("LYFT", null, "Freeze", 11, 550, "LYFT", "FREEZE"),
  p("LYFT", null, "Freeze 2", 11, 550, "LYFT", "FREEZE 2"),
  p("LYFT", null, "Freeze 4", 11, 530, "LYFT", "FREEZE 4"),
  p("LYFT", null, "Freeze X-Strong", 11, 530, "LYFT", "FREEZE X-Strong"),
  p("LYFT", null, "Ice Cool 3", 11, 530, "LYFT", "ICE COOL 3"),
  p("LYFT", null, "Ice Cool Slim", 11, 520, "LYFT", "ICE COOL SLIM"),
  p("LYFT", null, "Ice Cool Slim Strong", 11, 510, "LYFT", "ICE COOL SLIM STRONG"),
  p("LYFT", null, "Ice Cool Strong", 11, 510, "LYFT", "ICE COOL STRONG"),

  p("RED", null, "Barberry", 18, 540, "RED", "Barberry"),
  p("RED", null, "Cola", 18, 540, "RED", "Cola"),
  p("RED", null, "Ice Tarragon", 18, 520, "RED", "Ice Tarragon"),
  p("RED", null, "Lemon Cheesecake", 18, 550, "RED", "Lemon Cheesecake"),
  p("RED", null, "Mint Chocolate", 18, 540, "RED", "Mint Chocolate"),
  p("RED", null, "Original", 18, 530, "RED", "Original"),
  p("RED", null, "Strawberry Corn Arctic", 18, 540, "RED", "Strawberry-Corn-Arctic"),
  p("RED", null, "Ultra Mint", 18, 530, "RED", "Ultra mint"),
  p("RED", "X Series", "X Series 1", 18, 520, "RED", "X SERIAS 1"),
  p("RED", "X Series", "X Series 2", 18, 510, "RED", "X SERIES 2"),
  p("RED", "X Series", "X Series 3", 18, 510, "RED", "X SERIES 3"),
  p("RED", null, "X-Strong Original", 18, 540, "RED", "X-STRONG ORIGINAL"),

  p("SIBERIA", null, "Siberia", 43, 530, "SIBERIA", "SIBERIA"),

  p("ST", null, "ПроSTо X-name", 50, 500, "ST", "ПроSTо X-name"),
  p("ST", null, "Freeze Mint", 75, 500, "ST", "Freeze mint 75mg"),
  p("ST", null, "Lime Delight", 55, 500, "ST", "Lime delight 55mg"),
  p("ST", null, "Luxury Mint", 65, 510, "ST", "Luxury mint 65mg"),
  p("ST", null, "Menthol", 45, 550, "ST", "Menthol 45mg"),
  p("ST", null, "Royal Mint 120 Big", 120, 510, "ST", "Royal mint 120mg Big"),
  p("ST", null, "Royal Mint 120", 120, 550, "ST", "Royal mint 120mg"),

  p("ST вата", null, "Apple Energy Drink", 16, 530, "ST вата", "Apple-Energy Drink "),
  p("ST вата", null, "Blackberry", 16, 540, "ST вата", "Blackberry"),
  p("ST вата", null, "Caramel Ice Cream", 16, 500, "ST вата", "Caramel Ice Cream"),
  p("ST вата", null, "Citrus Mix", 16, 530, "ST вата", "Citrus Mix"),
  p("ST вата", null, "Ice Strawberries", 16, 530, "ST вата", "Ice Strawberries"),
  p("ST вата", null, "Mint Bubble Gum", 16, 530, "ST вата", "Mint-Bubble Gum"),
  p("ST вата", null, "Mint Candys", 16, 540, "ST вата", "Mint Candys"),
  p("ST вата", null, "Royal Mint", 16, 540, "ST вата", "Royal Mint"),

  p("VELO", null, "Crispy Peppermint", 10, 540, "VELO", "Crispy Peppermint"),
  p("VELO", null, "Freeze", 10, 540, "VELO", "Freeze"),
  p("VELO", null, "Mighty Peppermint 4", 10, 500, "VELO", "Mighty Peppermint 4"),
  p("VELO", null, "Mighty Peppermint", 10, 540, "VELO", "Mighty Peppermint"),
  p("VELO", null, "Ice Cool", 10, 520, "VELO", "UsBut Ice Cool"),
  p("VELO", null, "Freeze Mix", 10, 530, "VELO", "UzBut Freeze"),

  p("VOLKI", null, "Вишня", 16, 500, "VOLKI", "Вишня"),
  p("VOLKI", null, "Жвачка тутти фрутти", 16, 500, "VOLKI", "Жвачка тутти фрутти"),
  p("VOLKI", null, "Классический с мятой", 16, 520, "VOLKI", "Классический с мятой"),
  p("VOLKI", null, "Кола", 16, 520, "VOLKI", "Кола"),
  p("VOLKI", null, "Яблоко", 16, 510, "VOLKI", "Яблоко"),

  p("Стиль", null, "Berries Frost", 13, 550, "Стиль", "Berries Frost"),
  p("Стиль", null, "Bubble Gum", 13, 500, "Стиль", "Bubble Gum"),
  p("Стиль", "Coffee Pouches", "Bailey's", 13, 500, "Стиль", "COFFEE POUCHES Bailey_s"),
  p("Стиль", "Coffee Pouches", "Dr.paper", 13, 550, "Стиль", "COFFEE POUCHES Dr.paper"),
  p("Стиль", "Coffee Pouches", "Mint", 13, 520, "Стиль", "COFFEE POUCHES Mint"),
  p("Стиль", "Coffee Pouches", "Orange Raf", 13, 510, "Стиль", "COFFEE POUCHES Orange Raf"),
  p("Стиль", null, "Cool Dry", 13, 510, "Стиль", "Cool Dry"),
  p("Стиль", null, "Dr.Pepper", 13, 510, "Стиль", "Dr.Pepper "),
  p("Стиль", null, "Extra Mint", 13, 550, "Стиль", "Extra mint"),
  p("Стиль", null, "Fanta Exotic", 13, 500, "Стиль", "Fanta Exotic"),
  p("Стиль", null, "Frustyle", 13, 550, "Стиль", "Frustyle"),
  p("Стиль", null, "Gummy Bears", 13, 550, "Стиль", "Gummy Bears"),
  p("Стиль", null, "Ice Grapes", 13, 540, "Стиль", "Ice Grapes"),
  p("Стиль", null, "Ice Tsunami OVI", 13, 500, "Стиль", "Ice Tsunami _OVI_"),
  p("Стиль", null, "Menthol", 13, 540, "Стиль", "Menthol"),
  p("Стиль", null, "Mint", 13, 530, "Стиль", "Mint"),
  p("Стиль", null, "Monster Mango Loco", 13, 500, "Стиль", "Monster Mango Loco"),
  p("Стиль", null, "Mountain Dew Voltage", 13, 500, "Стиль", "Mountain Dew Voltage"),
  p("Стиль", null, "Pineapple Juice", 13, 500, "Стиль", "Pineapple Juice"),
  p("Стиль", null, "Sprite Watermelon", 13, 510, "Стиль", "Sprite Watermelon"),
  p("Стиль", null, "Tropic Breeze", 13, 510, "Стиль", "Tropic Breeze"),
  p("Стиль", null, "Wild Apple", 13, 540, "Стиль", "Wild Apple"),
];
